version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  vue: # name of the first service
    build: client # specify the directory of the Dockerfile
    ports:
      - "8080:80" # specify port forewarding
    volumes:
      - ./client:/app # will enable changes made to the vue app reflect in the container

  express: #name of the second service
    build: server # specify the directory of the Dockerfile
    ports:
      - "8081:8081" #specify ports forewarding
    links: # creates connection to service with name of service as the host name
      - mongodatabase

  mongodatabase: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    volumes:
      - /Users/jonathanorozco/Documents/GitHub.nosync/mongodb/data:/data/db