export default {

	// mutations
	SET_TOKEN: 'SET_TOKEN',
	SET_USER: 'SET_USER',
	FETCH_ARTICLES: 'FETCH_ARTICLES',
	FETCH_REALMS: 'FETCH_REALMS',
	FETCH_TAGS: 'FETCH_TAGS',
	FETCH_BY_TAG: 'FETCH_BY_TAG',
	UPDATE_ARTICLE: 'UPDATE_ARTICLE',
	SET_SINGLE_ARTICLE: 'SET_SINGLE_ARTICLE',
	UPDATE_ARTICLE_CONTENT: 'UPDATE_ARTICLE_CONTENT',
	ADD_TAGS: 'ADD_TAGS',
	SET_TAG: 'SET_TAG',
	SET_TAGS: 'SET_TAGS',
	REMOVE_TAG: 'REMOVE_TAG',
	REMOVE_POST_TAG: 'REMOVE_POST_TAG',
	POST_ARTICLE: 'POST_ARTICLE',
	PUSH_VIEWED: 'PUSH_VIEWED',
	DELETE_ARTICLE: 'DELETE_ARTICLE',
	FETCH_ARTICLE: 'FETCH_ARTICLE',
	AUTH_REQUEST: 'AUTH_REQUEST',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_ERR: 'AUTH_ERROR',

	// add hard coded string values here
}
