export default {
	SET_TOKEN: 'SET_TOKEN',
	SET_USER: 'SET_USER',
	FETCH_ARTICLES: 'FETCH_ARTICLES',
	UPDATE_ARTICLE: 'UPDATE_ARTICLE',
	POST_ARTICLE: 'POST_ARTICLE',
	DELETE_ARTICLE: 'DELETE_ARTICLE',
	FETCH_ARTICLE: 'FETCH_ARTICLE'
}
